pipeline {
    environment {
    registry = "raghava447/ecomm-authsrv"
    registryCredential = 'dockerhub'
    dockerImage = ''
    }

    agent any
    stages {
            stage('Cloning our Git') {
                steps {
                git 'https://github.com/raghavanfsd/ecomm-graphql-microservices.git'
                }
            }

            stage('Building Docker Image') {
                steps {
                    script {
                        sh "pwd"
                        dir('auth') {
                          dockerImage = docker.build registry + ":$BUILD_NUMBER"
                        }
                        sh "pwd"
                    }
                }
            }

            stage('Deploying Docker Image to Dockerhub') {
                steps {
                    script {
                        docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                        }
                    }
                }
            }

            stage('Cleaning Up') {
                steps{
                  sh "docker rmi --force $registry:$BUILD_NUMBER"
                }
            }
        }
    }
